apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rhtap-devfile-multi-component-f1sn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-sxbk-tenant/mc-two-scenarios/devfile-sample-python-basic-rhtap-devfile-multi-component-f1sn@sha256:8de62e91e63137d6ecb4584282f23fc4aa7f004a5b57dfec115051550be23681
        name: my-python
        resources: {}
status: {}
