apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-f1sn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-rhtap-devfile-multi-component-f1sn
    app.kubernetes.io/part-of: mc-two-scenarios
  name: devfile-sample-python-basic-rhtap-devfile-multi-component-f1sn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-f1sn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-f1sn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-sxbk-tenant/mc-two-scenarios/devfile-sample-python-basic-rhtap-devfile-multi-component-f1sn@sha256:8de62e91e63137d6ecb4584282f23fc4aa7f004a5b57dfec115051550be23681
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
